In [1]:
import pandas as pd
from dotenv import load_dotenv

# Explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
# Load .env variables
_ = load_dotenv(dotenv_path=f"{Path().resolve().parents[1]}/src/.env")

# with the new api
from importnb import imports
with imports("ipynb"):
    from utils import df_from_csv, df_pm25_to_df_aqi, plot_hist, plot_boxes, plot_lines, df_to_csv

PM2.5: 35.9, AQI: 102
PM2.5: 35.9, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 35.5, Max: 55.4
AQI: 102, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 101, Max: 150

## PM2.5 to AQI

In [2]:
# Load Raw Data
df_pm25_clean = df_from_csv("pm25_clean.csv", datafolder="1_clean")

# Check Data Types
print(df_pm25_clean.dtypes)

# Sorting by Descending
df_pm25_clean = df_pm25_clean.sort_values(by='DATETIME', ascending=False)

df_pm25_clean.head()

2024-03-01 17:19:49.629 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/1_clean/pm25_clean.csv

TANGARA_3BEA    float64
TANGARA_421A    float64
TANGARA_422A    float64
TANGARA_5636    float64
TANGARA_D282    float64
dtype: object

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2024-01-07 23:59:30-05:00,11.0,NaN,NaN,NaN,13.0
2024-01-07 23:59:00-05:00,12.0,NaN,NaN,NaN,11.0
2024-01-07 23:58:30-05:00,10.0,NaN,NaN,NaN,12.0
2024-01-07 23:58:00-05:00,11.0,NaN,NaN,NaN,13.0
2024-01-07 23:57:30-05:00,11.0,NaN,NaN,NaN,12.0

## Descriptive Statistics

In [3]:
# Describe Data
df_pm25_clean.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count  22100.000000  19606.000000  19455.000000  20740.000000  21124.000000
mean       6.309186      5.793890      5.757903      6.001639      7.129426
std        3.094601      2.642077      2.736385      2.806452      3.512930
min        1.000000      1.000000      1.000000      1.000000      1.000000
25%        4.000000      4.000000      4.000000      4.000000      5.000000
50%        6.000000      5.000000      5.000000      6.000000      6.000000
75%        8.000000      7.000000      7.000000      8.000000      9.000000
max       16.000000     14.000000     14.000000     14.000000     17.000000

## Group by hour on DATETIME and resample by mean

In [4]:
# Resample mean grouping by hour on DATETIME
df_pm25_clean = df_pm25_clean.resample('H').mean()

# Sorting by Descending
df_pm25_clean = df_pm25_clean.sort_values(by='DATETIME', ascending=False)

df_pm25_clean.head()

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2024-01-07 23:00:00-05:00,10.508333,NaN,NaN,NaN,11.733333
2024-01-07 22:00:00-05:00,11.608333,NaN,NaN,NaN,13.058333
2024-01-07 21:00:00-05:00,10.271028,NaN,NaN,NaN,11.615385
2024-01-07 20:00:00-05:00,6.081081,NaN,NaN,NaN,6.935185
2024-01-07 19:00:00-05:00,5.042373,NaN,NaN,NaN,5.781818

## Descriptive Statistics

In [5]:
# Describe Data
df_pm25_clean.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count    200.000000    180.000000    178.000000    185.000000    195.000000
mean       6.644485      6.048034      6.018895      6.252652      7.271284
std        3.229138      2.678095      2.766386      2.845643      3.395306
min        1.268908      1.153846      1.177966      1.224138      1.406780
25%        4.359440      4.096464      3.882632      4.177966      4.737228
50%        6.016982      5.698179      5.525533      5.730435      6.517544
75%        8.419492      7.660417      7.588235      7.890756      9.266949
max       16.000000     14.000000     13.851852     14.000000     16.829268

## Movil 24h, Rolling Function in Pandas

In [6]:
# Movil 24h, Rolling Function in Pandas
df_pm25_clean = df_pm25_clean.rolling(window=24, min_periods=1).mean()

df_pm25_clean.head()

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2024-01-07 23:00:00-05:00,10.508333,NaN,NaN,NaN,11.733333
2024-01-07 22:00:00-05:00,11.058333,NaN,NaN,NaN,12.395833
2024-01-07 21:00:00-05:00,10.795898,NaN,NaN,NaN,12.135684
2024-01-07 20:00:00-05:00,9.617194,NaN,NaN,NaN,10.835559
2024-01-07 19:00:00-05:00,8.702230,NaN,NaN,NaN,9.824811

## Descriptive Statistics

In [7]:
# Describe Data
df_pm25_clean.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count    216.000000    203.000000    203.000000    203.000000    216.000000
mean       6.938438      6.440853      6.405231      6.760464      7.638796
std        1.893726      1.617501      1.775150      1.962317      1.992297
min        4.495070      4.338830      4.045024      4.449846      4.986692
25%        5.252859      5.045265      4.897323      5.108979      5.886646
50%        6.849236      5.880141      5.772136      6.112652      7.035042
75%        8.271559      7.621430      7.640126      8.092312      9.299757
max       12.138202     10.445540     10.512994     11.000000     12.561199

## Filter just the last 24 hours

In [8]:
# Sorting by Ascending
df_pm25_clean = df_pm25_clean.sort_values(by='DATETIME', ascending=True)

# Filter just the las 24 hours
df_pm25_clean = df_pm25_clean.loc[df_pm25_clean.index >= df_pm25_clean.index[0] + pd.Timedelta(hours=24)]

df_pm25_clean.head()

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2023-12-31 00:00:00-05:00,10.703645,9.298652,9.433603,9.726932,11.211458
2023-12-31 01:00:00-05:00,10.980615,9.555414,9.673709,9.975332,11.505463
2023-12-31 02:00:00-05:00,11.325282,9.914049,9.993092,10.302728,11.888728
2023-12-31 03:00:00-05:00,11.594531,10.180071,10.243163,10.550781,12.190517
2023-12-31 04:00:00-05:00,12.043779,10.429346,10.473505,10.782402,12.464822

In [9]:
df_pm25_clean.tail()

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2024-01-07 19:00:00-05:00,8.702230,NaN,NaN,NaN,9.824811
2024-01-07 20:00:00-05:00,9.617194,NaN,NaN,NaN,10.835559
2024-01-07 21:00:00-05:00,10.795898,NaN,NaN,NaN,12.135684
2024-01-07 22:00:00-05:00,11.058333,NaN,NaN,NaN,12.395833
2024-01-07 23:00:00-05:00,10.508333,NaN,NaN,NaN,11.733333

## Descriptive Statistics

In [10]:
# Describe Data
df_pm25_clean.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count    192.000000    179.000000    179.000000    179.000000    192.000000
mean       6.914239      6.417271      6.401447      6.774978      7.641009
std        1.925649      1.646974      1.817515      2.020842      2.024872
min        4.495070      4.338830      4.045024      4.449846      4.986692
25%        5.227114      5.040195      4.897323      5.108979      5.886646
50%        6.550326      5.804417      5.727283      5.931745      6.941062
75%        8.271559      7.621430      7.666909      8.107671      9.323115
max       12.138202     10.445540     10.512994     11.000000     12.561199

## PM2.5 to AQI

In [11]:
# AQI DataFrame Sensors
df_aqi = df_pm25_to_df_aqi(df_pm25_clean)
df_aqi = df_aqi.astype('float')
df_aqi.head()

2024-03-01 17:19:49.899 | DEBUG    | utils:df_pm25_to_df_aqi:677 - PM2.5 DataFrame Sensors to AQI DataFrame Sensors: <class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 192 entries, 2023-12-31 00:00:00-05:00 to 2024-01-07 23:00:00-05:00
Freq: H
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TANGARA_3BEA  192 non-null    Int64
 1   TANGARA_421A  179 non-null    Int64
 2   TANGARA_422A  179 non-null    Int64
 3   TANGARA_5636  179 non-null    Int64
 4   TANGARA_D282  192 non-null    Int64
dtypes: Int64(5)
memory usage: 9.9 KB

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2023-12-31 00:00:00-05:00,45.0,39.0,40.0,41.0,47.0
2023-12-31 01:00:00-05:00,46.0,40.0,41.0,42.0,48.0
2023-12-31 02:00:00-05:00,48.0,42.0,42.0,43.0,50.0
2023-12-31 03:00:00-05:00,49.0,43.0,43.0,45.0,52.0
2023-12-31 04:00:00-05:00,50.0,44.0,44.0,46.0,52.0

## Describe Statistics

In [12]:
# Describe Data
df_aqi.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count    192.000000    179.000000    179.000000    179.000000    192.000000
mean      29.338542     27.206704     27.145251     28.659218     32.312500
std        8.025807      6.843906      7.589993      8.406863      8.408189
min       19.000000     18.000000     17.000000     19.000000     21.000000
25%       22.000000     21.000000     21.000000     22.000000     25.000000
50%       28.000000     25.000000     24.000000     25.000000     29.500000
75%       35.000000     32.000000     33.000000     34.000000     39.000000
max       51.000000     44.000000     44.000000     46.000000     53.000000

## Histograms

In [13]:
# Plot Histograms
plot_hist(df_aqi)

2024-03-01 17:19:49.951 | DEBUG    | utils:plot_hist:514 - Plot Histograms: False

## Boxplots

In [14]:
# Plot Boxplots
plot_boxes(df_aqi)

2024-03-01 17:19:49.962 | DEBUG    | utils:plot_boxes:547 - Plot Boxplots: False

## Lineplots

In [15]:
# Plot Lineplots
plot_lines(df_aqi)

2024-03-01 17:19:49.973 | DEBUG    | utils:plot_lines:588 - Plot Lineplots: False

In [16]:
# Save AQI Data Frame Sensors into CSV file
df_to_csv(df_aqi, "aqi.csv", datafolder='2_features')

2024-03-01 17:19:49.990 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/aqi.csv