In [1]:
import os
import math
from dotenv import load_dotenv

# Explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
# Load .env variables
_ = load_dotenv(dotenv_path=f"{Path().resolve().parents[1]}/src/.env")

# with the new api
from importnb import imports
with imports("ipynb"):
    from utils import to_timestamp, df_data_sensors, missing_data, correlation_data, df_to_csv, df_from_csv

PM2.5: 35.9, AQI: 102
PM2.5: 35.9, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 35.5, Max: 55.4
AQI: 102, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 101, Max: 150

## PM2.5 Raw Data

In [2]:
# Load Tangaras
df_tangaras = df_from_csv("tangaras.csv", dtindex=False)

print(f"Total Tangara Sensors: {len(df_tangaras)}")

df_tangaras.head()

2024-03-01 17:13:31.401 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/0_raw/tangaras.csv

Total Tangara Sensors: 16

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_2BDE,d29e6de,D29ESP32DE52BDE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
1,TANGARA_3B7E,d29e6de,D29ESP32DE53B7E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_3BEA,d29e6de,D29ESP32DE53BEA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
3,TANGARA_421A,d29e6de,D29ESP32DE5421A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
4,TANGARA_422A,d29e6de,D29ESP32DE5422A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

In [3]:
# Filter by ID_TANGARA_REFERENCE and IDS_TANGARA_TARGETS

# Tangara Sensor Reference
ID_TANGARA_REFERENCE=os.getenv("ID_TANGARA_REFERENCE", None)
# Tangara Sensors Target
IDS_TANGARA_TARGETS=os.getenv("IDS_TANGARA_TARGETS", None)

print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}")
print(f"Tangara Sensors Target: {IDS_TANGARA_TARGETS}")

ids = IDS_TANGARA_TARGETS.split(',') if IDS_TANGARA_TARGETS else []
ids.append(ID_TANGARA_REFERENCE)

df_tangaras = df_tangaras[df_tangaras['ID'].isin(ids)]

print(f"Total Tangara Sensors: {len(df_tangaras)}")

df_tangaras.head()

Tangara Sensor Reference: TANGARA_5636
Tangara Sensors Target: TANGARA_39D6,TANGARA_2BDE,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
Total Tangara Sensors: 6

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_2BDE,d29e6de,D29ESP32DE52BDE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_3BEA,d29e6de,D29ESP32DE53BEA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
3,TANGARA_421A,d29e6de,D29ESP32DE5421A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
4,TANGARA_422A,d29e6de,D29ESP32DE5422A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
5,TANGARA_5636,d29e6de,D29ESP32DE85636,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

In [4]:
# Start Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
START_ISO8601_DATETIME = os.getenv("START_ISO8601_DATETIME", None)
start_timestamp = to_timestamp(START_ISO8601_DATETIME)
# End Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
END_ISO8601_DATETIME = os.getenv("END_ISO8601_DATETIME", None)
end_timestamp = to_timestamp(os.getenv("END_ISO8601_DATETIME", None))

# GROUP BY TIME
GROUP_BY_TIME = os.getenv("GROUP_BY_TIME", None)

print(f'Since: {START_ISO8601_DATETIME} -> {start_timestamp}, Until: {END_ISO8601_DATETIME} -> {end_timestamp}')
print(f"Group by Time: {GROUP_BY_TIME}")

2024-03-01 17:13:31.450 | DEBUG    | utils:to_timestamp:99 - datetime_iso8601: 2023-12-30T00:00:00-05:00, Timestamp: 1703912400000
2024-03-01 17:13:31.452 | DEBUG    | utils:to_timestamp:99 - datetime_iso8601: 2024-01-07T23:59:59-05:00, Timestamp: 1704689999000

Since: 2023-12-30T00:00:00-05:00 -> 1703912400000, Until: 2024-01-07T23:59:59-05:00 -> 1704689999000
Group by Time: 30s

In [5]:
# PM2.5 Data Frame Sensors
df_pm25_raw = df_data_sensors(df_tangaras, start_timestamp, end_timestamp, 'pm25', GROUP_BY_TIME)
df_pm25_raw.head()
#df_pm25_raw.shape

2024-03-01 17:13:31.464 | DEBUG    | utils:query_measure:192 - sql_query: SELECT last("pm25") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE52BDE') AND time >= 1703912400000ms AND time <= 1704689999000ms GROUP BY time(30s) fill(null); SELECT last("pm25") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE53BEA') AND time >= 1703912400000ms AND time <= 1704689999000ms GROUP BY time(30s) fill(null); SELECT last("pm25") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE5421A') AND time >= 1703912400000ms AND time <= 1704689999000ms GROUP BY time(30s) fill(null); SELECT last("pm25") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE5422A') AND time >= 1703912400000ms AND time <= 1704689999000ms GROUP BY time(30s) fill(null); SELECT last("pm25") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE85636') AND time >= 1703912400000ms AND time <= 1704689999000ms GROUP BY time(30s) fill(null); SELECT last("pm25") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE8D282') AND time >= 1703912400000ms AND time <= 1704689999000ms GROUP BY time(30s) fill(null)
2024-03-01 17:13:33.782 | DEBUG    | utils:request_influxdb:131 - response: <Response [200]>
2024-03-01 17:13:34.814 | DEBUG    | utils:df_data_sensors:480 - Measure Data Frame Sensors: <class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 25920 entries, 2023-12-30 00:00:00-05:00 to 2024-01-07 23:59:30-05:00
Freq: 30S
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TANGARA_2BDE  17491 non-null  float64
 1   TANGARA_3BEA  23274 non-null  float64
 2   TANGARA_421A  20774 non-null  float64
 3   TANGARA_422A  20796 non-null  float64
 4   TANGARA_5636  22104 non-null  float64
 5   TANGARA_D282  22245 non-null  float64
dtypes: float64(6)
memory usage: 1.4 MB

,TANGARA_2BDE,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,,
2023-12-30 00:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN
2023-12-30 00:00:30-05:00,10.0,8.0,7.0,6.0,8.0,8.0
2023-12-30 00:01:00-05:00,10.0,7.0,8.0,7.0,7.0,8.0
2023-12-30 00:01:30-05:00,9.0,8.0,8.0,7.0,7.0,7.0
2023-12-30 00:02:00-05:00,9.0,8.0,7.0,7.0,7.0,7.0

## Descriptive Statistics

In [6]:
# Describe Data
df_pm25_raw.describe()

,TANGARA_2BDE,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
count,17491.000000,23274.000000,20774.000000,20796.000000,22104.000000,22245.000000
mean,9.437253,7.956475,7.407336,7.466436,7.863147,9.167049
std,76.018022,50.581405,45.621187,45.306838,65.148359,94.734987
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,5.000000,4.000000,4.000000,4.000000,4.000000,5.000000
50%,7.000000,6.000000,6.000000,6.000000,6.000000,7.000000
75%,10.000000,9.000000,8.000000,8.000000,8.000000,10.000000
max,8587.000000,6030.000000,5959.000000,4917.000000,8154.000000,13475.000000

## Missing Data

In [7]:
import warnings
warnings.filterwarnings('ignore')

# Missing Data Threshold
threshold_data = float(os.getenv("THRESHOLD_MISSING_DATA", None))
print(f'Threshold Missing Data: {int(threshold_data * 100)}%')

# For each Tangara sensor
for id_tangara_sensor in df_pm25_raw.columns:
    df_pm25_sensor = df_pm25_raw[[id_tangara_sensor]]
    # To be checked
    to_be_checked, data_percent, missing_data_percent = missing_data(df_pm25_sensor, threshold_data)
    if to_be_checked:
        print(f"Tangara Sensor: {id_tangara_sensor}, To be checked: {to_be_checked}, Data: {data_percent}%, Missing Data: {missing_data_percent}%, Threshold: {threshold_data}%")

        # Drop Tangara Sensor from original dataframe
        df_pm25_raw = df_pm25_raw.drop(id_tangara_sensor, axis=1)

2024-03-01 17:13:34.882 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_2BDE, To be checked: True, Data: 67%, Missing Data: 33%, Threshold: 80%
2024-03-01 17:13:34.887 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_3BEA, To be checked: False, Data: 90%, Missing Data: 10%, Threshold: 80%
2024-03-01 17:13:34.890 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_421A, To be checked: False, Data: 80%, Missing Data: 20%, Threshold: 80%
2024-03-01 17:13:34.896 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_422A, To be checked: False, Data: 80%, Missing Data: 20%, Threshold: 80%
2024-03-01 17:13:34.899 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_5636, To be checked: False, Data: 85%, Missing Data: 15%, Threshold: 80%
2024-03-01 17:13:34.903 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_D282, To be checked: False, Data: 86%, Missing Data: 14%, Threshold: 80%

Threshold Missing Data: 80%
Tangara Sensor: TANGARA_2BDE, To be checked: True, Data: 67%, Missing Data: 33%, Threshold: 0.8%

## Data Correlation

In [8]:
# Data Correlation Threshold
threshold_correlation = float(os.getenv("THRESHOLD_CORRELATION_DATA", None))
print(f'Threshold Correlation Data: {int(threshold_correlation * 100)}%')

# Tangara Sensor Reference
ID_TANGARA_REFERENCE=os.getenv("ID_TANGARA_REFERENCE", None)

# Tangara Sensors Target
IDS_TANGARA_TARGETS=os.getenv("IDS_TANGARA_TARGETS", None)
IDS_TANGARA_TARGETS = IDS_TANGARA_TARGETS.split(',') if IDS_TANGARA_TARGETS else ID_TANGARA_REFERENCE

# print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}, Tangara Sensors Target: {IDS_TANGARA_TARGETS}")

# Reference Tangara Sensor
df_tangara_reference = df_pm25_raw[[ID_TANGARA_REFERENCE]]

# For each Tangara Sensor Target
for id_tangara in IDS_TANGARA_TARGETS:
    if id_tangara in df_pm25_raw.columns:
        # Target Tangara Sensor
        df_tangara_target = df_pm25_raw[[id_tangara]]

        # To be checked
        if not math.isnan(df_tangara_reference.std()):
            has_corr, corr = correlation_data(df_tangara_reference, df_tangara_target, threshold_correlation)
            if not has_corr:
                print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}, Tangara Sensors Target: {id_tangara}, There is correlation: {has_corr}, Correlation: {float("{:.2f}".format(corr))}, Threshold: {threshold_correlation}")

                # Drop Tangara Sensor from original dataframe
                df_pm25_raw = df_pm25_raw.drop(id_tangara, axis=1)

2024-03-01 17:13:34.934 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_3BEA, There is correlation: True, Correlation: 0.89, Threshold: 0.7
2024-03-01 17:13:34.952 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_421A, There is correlation: True, Correlation: 0.88, Threshold: 0.7
2024-03-01 17:13:34.972 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_422A, There is correlation: True, Correlation: 0.97, Threshold: 0.7
2024-03-01 17:13:34.989 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_5636, There is correlation: True, Correlation: 1.0, Threshold: 0.7
2024-03-01 17:13:35.003 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_D282, There is correlation: True, Correlation: 0.95, Threshold: 0.7

Threshold Correlation Data: 70%

In [9]:
# Save PM2.5 Data Frame Sensors into CSV file
df_to_csv(df_pm25_raw, "pm25_raw.csv")

2024-03-01 17:13:35.602 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/0_raw/pm25_raw.csv